---
- name: Ensure Java is installed.
  package:
    name: "{{ java_package }}"
    state: present

- name: Set JAVA_HOME
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
